import json
import os
from datetime import datetime, timezone

import requests


TOKEN_URL = 'https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal'
MESSAGE_URL = 'https://open.feishu.cn/open-apis/im/v1/messages'


def get_feishu_config():
    webhook = first_env('DASHBOARD_FEISHU_WEBHOOK', 'FEISHU_ALERT_WEBHOOK')
    app_id = first_env('DASHBOARD_FEISHU_APP_ID', 'FEISHU_BOT_APP_ID', 'FEISHU_APP_ID')
    app_secret = first_env('DASHBOARD_FEISHU_APP_SECRET', 'FEISHU_BOT_APP_SECRET', 'FEISHU_APP_SECRET')
    chat_id = first_env('DASHBOARD_FEISHU_CHAT_ID', 'FEISHU_ALERT_CHAT_ID', 'FEISHU_CHAT_ID')
    return {
        'webhook': webhook,
        'app_id': app_id,
        'app_secret': app_secret,
        'chat_id': chat_id,
        'configured': bool(webhook or (app_id and app_secret and chat_id)),
    }


def send_dashboard_alert(triggered_alerts, all_alerts=None):
    config = get_feishu_config()
    if not config['configured']:
        return {'sent': False, 'reason': 'Feishu alert config is incomplete', 'config': redacted_config(config)}
    if not triggered_alerts:
        return {'sent': False, 'reason': 'No triggered alerts', 'config': redacted_config(config)}

    card = build_alert_card(triggered_alerts, all_alerts or triggered_alerts)
    if config.get('webhook'):
        return send_webhook_card(config['webhook'], card, config)

    token = get_tenant_token(config['app_id'], config['app_secret'])
    session = requests.Session()
    session.trust_env = False
    resp = session.post(
        MESSAGE_URL,
        params={'receive_id_type': 'chat_id'},
        headers={
            'Authorization': f'Bearer {token}',
            'Content-Type': 'application/json; charset=utf-8',
        },
        json={
            'receive_id': config['chat_id'],
            'msg_type': 'interactive',
            'content': json.dumps(card, ensure_ascii=False),
        },
        timeout=15,
    )
    resp.raise_for_status()
    result = resp.json()
    if result.get('code') != 0:
        return {'sent': False, 'reason': result.get('msg') or str(result), 'result': result, 'config': redacted_config(config)}
    return {'sent': True, 'message_id': result.get('data', {}).get('message_id', ''), 'config': redacted_config(config)}


def send_webhook_card(webhook, card, config):
    session = requests.Session()
    session.trust_env = False
    resp = session.post(
        webhook,
        json={'msg_type': 'interactive', 'card': card},
        timeout=15,
    )
    resp.raise_for_status()
    result = resp.json()
    if result.get('StatusCode') in (0, None) and result.get('code', 0) == 0:
        return {'sent': True, 'channel': 'webhook', 'config': redacted_config(config)}
    return {'sent': False, 'channel': 'webhook', 'reason': result.get('msg') or result.get('StatusMessage') or str(result), 'result': result, 'config': redacted_config(config)}


def get_tenant_token(app_id, app_secret):
    session = requests.Session()
    session.trust_env = False
    resp = session.post(TOKEN_URL, json={'app_id': app_id, 'app_secret': app_secret}, timeout=15)
    resp.raise_for_status()
    data = resp.json()
    if data.get('code') != 0:
        raise RuntimeError(f"Feishu auth failed: {data.get('msg') or data}")
    return data['tenant_access_token']


def build_alert_card(triggered_alerts, all_alerts):
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')
    fields = []
    for alert in triggered_alerts[:8]:
        metric = metric_label(alert['metric_name'])
        current = fmt(alert.get('current_value'))
        previous = fmt(alert.get('previous_value'))
        change = pct(alert.get('change_ratio'))
        threshold = pct(alert.get('threshold'))
        fields.append({
            'tag': 'div',
            'text': {
                'tag': 'lark_md',
                'content': f"**{metric}**\n当前：{current}｜上期：{previous}｜变化：{change}｜阈值：{threshold}",
            },
        })
    if len(triggered_alerts) > 8:
        fields.append({'tag': 'div', 'text': {'tag': 'lark_md', 'content': f"还有 {len(triggered_alerts) - 8} 条预警未展开。"}})

    window = triggered_alerts[0]
    elements = [
        {
            'tag': 'div',
            'text': {
                'tag': 'lark_md',
                'content': f"检测到 **{len(triggered_alerts)}** 个增长指标超过阈值。\n监控窗口：{window.get('window_start')} ~ {window.get('window_end')}",
            },
        },
        {'tag': 'hr'},
        *fields,
        {'tag': 'hr'},
        {
            'tag': 'note',
            'elements': [{'tag': 'plain_text', 'content': f"Generated by AgentOS dashboard_metrics_alert_check at {now}"}],
        },
    ]
    return {
        'config': {'wide_screen_mode': True},
        'header': {
            'title': {'tag': 'plain_text', 'content': 'iWeaver 增长指标预警'},
            'template': 'red',
        },
        'elements': elements,
    }


def first_env(*names):
    for name in names:
        value = os.getenv(name, '').strip()
        if value:
            return value
    return ''


def redacted_config(config):
    return {
        'webhook_configured': bool(config.get('webhook')),
        'app_id_configured': bool(config.get('app_id')),
        'app_secret_configured': bool(config.get('app_secret')),
        'chat_id_configured': bool(config.get('chat_id')),
    }


def metric_label(name):
    labels = {
        'registration_users': '注册用户数',
        'registration_rate': '注册率',
        'paid_users': '付费用户',
        'renewal_orders': '续费订单',
        'payment_amount': '付费金额',
    }
    return labels.get(name, name)


def fmt(value):
    if value is None:
        return '-'
    number = float(value)
    if abs(number) >= 1000:
        return f'{number:,.2f}'.rstrip('0').rstrip('.')
    return f'{number:.4f}'.rstrip('0').rstrip('.')


def pct(value):
    if value is None:
        return '-'
    return f'{float(value) * 100:.2f}%'
