import importlib.util, json, os, shutil, sqlite3, tempfile, time, unittest
from pathlib import Path

APP=Path('/private/tmp/x-browse-v2-staging/controller/app.py')

class LifecycleTests(unittest.TestCase):
 def setUp(self):
  self.tmp=tempfile.mkdtemp(prefix='x-controller-test-',dir='/private/tmp');self.db=str(Path(self.tmp)/'console.db')
  os.environ.update(X_CONSOLE_DB=self.db,X_CONSOLE_ADMIN_PASSWORD='a',X_CONSOLE_SESSION_SECRET='s',X_CONSOLE_WORKER_SECRET='w')
  spec=importlib.util.spec_from_file_location('controller_app_'+str(time.time_ns()),APP);self.m=importlib.util.module_from_spec(spec);spec.loader.exec_module(self.m);self.m.init()
 def tearDown(self):shutil.rmtree(self.tmp,ignore_errors=True)
 def c(self):return self.m.conn()
 def worker(self,w='w1',tokens=True,executions=None,seen=None,capacity=3,active_profiles=None,active_ports=None):
  c=self.c();caps=['execution_tokens'] if tokens else [];details={'capacity':capacity,'available_slots':capacity,'capabilities':caps,'protocol_version':'2' if tokens else '1','executions':executions or [],'active_job_ids':[],'active_profile_ids':active_profiles or [],'active_proxy_ports':active_ports or []};n=seen if seen is not None else self.m.now();c.execute('INSERT OR REPLACE INTO workers(worker_id,status,last_seen_at,current_job_id,details_json,capacity) VALUES(?,?,?,?,?,?)',(w,'idle',n,None,self.m.jd(details),capacity));c.close()
 def handler(self):
  h=object.__new__(self.m.H);h.responses=[];h.out=lambda status,data,*args,**kwargs:h.responses.append((status,data));return h
 def make_job(self,aid=10,kind='browse',tokens=True):
  self.worker(tokens=tokens);c=self.c();c.execute('BEGIN IMMEDIATE');c.execute("UPDATE settings SET value='0'");a=self.m.acc(c,aid);rid,jid,_=self.m.create(c,a,300,'manual',kind=kind,manual=True);generation=1;token='token-1' if tokens else None;n=self.m.now();c.execute("UPDATE jobs SET status='running',worker_id='w1',execution_generation=?,execution_token=?,execution_state='running',lease_expires_at=? WHERE id=?",(generation,token,n+120,jid));c.execute("UPDATE runs SET status='running',started_at=? WHERE id=?",(n,rid));c.commit();j=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();c.close();return rid,jid,j
 def test_migration_and_unique_retry_index(self):
  c=self.c();jobs={x['name'] for x in c.execute('PRAGMA table_info(jobs)')};runs={x['name'] for x in c.execute('PRAGMA table_info(runs)')};indexes={x['name'] for x in c.execute('PRAGMA index_list(runs)')};c.close()
  self.assertTrue({'execution_generation','execution_token','execution_state','cleanup_state','cleanup_confirmed_at','last_forward_progress_at','quarantine_reason','terminal_code'}<=jobs)
  self.assertTrue({'failure_code','failure_detail','cleanup_confirmed','retry_block_reason'}<=runs);self.assertIn('runs_retry_unique',indexes)
 def test_paused_scheduler_creates_nothing(self):
  self.worker();c=self.c();self.m.plan(c,10);before=c.execute('SELECT COUNT(*) FROM jobs').fetchone()[0];self.m.scheduler_fill(c,self.m.now());after=c.execute('SELECT COUNT(*) FROM jobs').fetchone()[0];c.close();self.assertEqual(before,after)
 def test_token_and_stale_token_validation(self):
  rid,jid,j=self.make_job();h=object.__new__(self.m.H);c=self.c();ok,_=h.validate_execution(c,'w1',j,{'execution_token':'token-1'});self.assertTrue(ok)
  with self.assertRaises(self.m.E) as x:h.validate_execution(c,'w1',j,{'execution_token':'stale'})
  self.assertEqual(x.exception.code,'stale_execution_token');valid,directive=h.validate_execution(c,'w1',j,{'execution_token':'stale'},True);c.close();self.assertFalse(valid);self.assertEqual(directive,'stop_and_cleanup')
 def test_terminal_progress_is_stable_and_does_not_write(self):
  rid,jid,j=self.make_job();c=self.c();self.m.finish(c,j,'succeeded',10,cleanup_confirmed=True);events=c.execute('SELECT COUNT(*) FROM events').fetchone()[0];items=c.execute('SELECT COUNT(*) FROM items').fetchone()[0];terminal=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();h=object.__new__(self.m.H);valid,directive=h.validate_execution(c,'w1',terminal,{'execution_token':'token-1'},True);self.assertTrue(valid);self.assertEqual(directive,None);self.assertIn(terminal['status'],self.m.TERMINAL);self.assertEqual(events,c.execute('SELECT COUNT(*) FROM events').fetchone()[0]);self.assertEqual(items,c.execute('SELECT COUNT(*) FROM items').fetchone()[0]);c.close()
 def test_duplicate_finish_settles_budget_once(self):
  rid,jid,j=self.make_job();c=self.c();p0=c.execute('SELECT * FROM daily_plans WHERE account_id=10 AND plan_date=?',(self.m.today(),)).fetchone();self.assertTrue(self.m.finish(c,j,'succeeded',100,cleanup_confirmed=True));j2=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();self.assertFalse(self.m.finish(c,j2,'succeeded',200,cleanup_confirmed=True));p=c.execute('SELECT * FROM daily_plans WHERE id=?',(p0['id'],)).fetchone();c.close();self.assertEqual(p['used_seconds'],100);self.assertEqual(p['reserved_seconds'],0)
 def test_settlement_uses_last_accepted_elapsed_floor(self):
  rid,jid,j=self.make_job();c=self.c();c.execute('UPDATE jobs SET elapsed_seconds=87 WHERE id=?',(jid,));j=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();self.assertTrue(self.m.finish(c,j,'failed',0,'browser failed',failure_code='browser_crashed',cleanup_confirmed=True));run=c.execute('SELECT * FROM runs WHERE id=?',(rid,)).fetchone();plan=c.execute('SELECT * FROM daily_plans WHERE id=?',(run['plan_id'],)).fetchone();j2=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();self.assertFalse(self.m.finish(c,j2,'failed',200,cleanup_confirmed=True));plan2=c.execute('SELECT * FROM daily_plans WHERE id=?',(run['plan_id'],)).fetchone();c.close();self.assertEqual(run['actual_seconds'],87);self.assertEqual(plan['used_seconds'],87);self.assertEqual(plan2['used_seconds'],87)
 def test_precise_failure_code_policy(self):
  retryable={'webdriver_frozen','no_forward_progress','hard_runtime_exceeded','browser_start_failed','adspower_unavailable','controller_unavailable','browser_crashed'}
  never={'manual_profile_in_use','cleanup_uncertain'}
  self.assertTrue(retryable<=self.m.FAILURE_CODES);self.assertTrue(never<=self.m.FAILURE_CODES);self.assertTrue(retryable<=self.m.RETRYABLE_CODES);self.assertTrue(never.isdisjoint(self.m.RETRYABLE_CODES));self.assertIn('browser',self.m.RETRYABLE_CODES)
 def test_terminal_code_precedes_child_manual_cancel(self):
  rid,jid,j=self.make_job();c=self.c();c.execute("UPDATE jobs SET status='stopping',terminal_code='lease_expired',cleanup_state='requested' WHERE id=?",(jid,));c.execute("UPDATE runs SET status='cancel_requested' WHERE id=?",(rid,));c.close();h=self.handler();h.complete('w1',jid,{'execution_token':'token-1','status':'cancelled','actual_seconds':0,'error':'Cancelled by administrator','failure_code':'manual_cancel','cleanup_confirmed':True});c=self.c();run=c.execute('SELECT * FROM runs WHERE id=?',(rid,)).fetchone();jobrow=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();c.close();self.assertEqual(run['status'],'failed');self.assertEqual(run['failure_code'],'lease_expired');self.assertEqual(jobrow['terminal_code'],'lease_expired');self.assertEqual(run['retry_eligible'],1)
 def test_cleanup_uncertainty_quarantines_and_never_retries(self):
  rid,jid,j=self.make_job();c=self.c();c.execute("UPDATE settings SET value='0'");self.assertTrue(self.m.finish(c,j,'failed',20,'network error',failure_code='network',cleanup_confirmed=False));r=c.execute('SELECT * FROM runs WHERE id=?',(rid,)).fetchone();job=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();c.close();self.assertEqual(job['status'],'quarantined');self.assertEqual(job['cleanup_state'],'uncertain');self.assertEqual(r['retry_eligible'],0);self.assertEqual(r['retry_block_reason'],'cleanup_uncertain')
 def test_heartbeat_ghost_mismatch_does_not_make_capacity_contradictory(self):
  self.worker(executions=[{'job_id':999,'execution_token':'ghost'}]);c=self.c();w=self.m.authoritative_workload(c);c.close();self.assertTrue(any(x['reason']=='heartbeat_ghost_or_terminal' for x in w['mismatches']));self.assertEqual(w['occupied'],1);self.assertEqual(w['available_slots'],2);self.assertEqual(w['capacity'],3)
 def test_capability_distinctions(self):
  self.worker();c=self.c();c.execute("UPDATE settings SET value='1'");c.execute("UPDATE accounts SET auto_schedule_enabled=1,daily_window_start='00:00',daily_window_end='00:01' WHERE id=10");a=self.m.acc(c,10);p=self.m.plan(c,10);h=object.__new__(self.m.H);self.assertIsNone(h.block_reason(c,a,p,'manual'));self.assertIsNone(h.block_reason(c,a,p,'probe'));self.assertEqual(h.block_reason(c,a,p,'auto'),'global_schedule_paused');c.close()
 def test_unique_retry_creation(self):
  rid,jid,j=self.make_job();c=self.c();self.m.finish(c,j,'failed',10,'network error',failure_code='network',cleanup_confirmed=True);c.execute("UPDATE settings SET value='0'");a=self.m.acc(c,10);c.execute("UPDATE jobs SET status='failed' WHERE id=?",(jid,));self.m.create(c,a,100,'retry','browse',rid,1);c.execute("UPDATE jobs SET status='failed' WHERE run_id=(SELECT MAX(id) FROM runs)")
  with self.assertRaises(self.m.E) as x:self.m.create(c,a,100,'retry','browse',rid,1)
  c.close();self.assertEqual(x.exception.code,'retry_exists')
 def test_new_protocol_lease_expiry_requests_cleanup_legacy_quarantines(self):
  rid,jid,j=self.make_job(tokens=True);c=self.c();c.execute('UPDATE jobs SET lease_expires_at=? WHERE id=?',(self.m.now()-1,jid));self.m.expire_leases(c,self.m.now());new=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();self.assertEqual(new['status'],'stopping');self.assertEqual(new['cleanup_state'],'requested');c.close()
  rid,jid,j=self.make_job(aid=11,tokens=False);c=self.c();c.execute('UPDATE jobs SET lease_expires_at=? WHERE id=?',(self.m.now()-1,jid));self.m.expire_leases(c,self.m.now());legacy=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();run=c.execute('SELECT * FROM runs WHERE id=?',(rid,)).fetchone();c.close();self.assertEqual(legacy['status'],'quarantined');self.assertEqual(legacy['cleanup_state'],'uncertain');self.assertEqual(run['cleanup_confirmed'],0)
 def test_terminal_and_unknown_heartbeat_directives_require_cleanup(self):
  rid,jid,j=self.make_job();c=self.c();self.m.finish(c,j,'succeeded',10,cleanup_confirmed=True);h=self.handler();self.assertEqual(h.directive_for_execution(c,'w1',{'job_id':jid,'execution_token':'token-1'},True)['directive'],'stop_and_cleanup');self.assertEqual(h.directive_for_execution(c,'w1',{'job_id':999},True)['directive'],'stop_and_cleanup');d=h.directive_for_execution(c,'w1',{'job_id':jid,'execution_token':'token-1','cleanup_confirmed':True},True);job=c.execute('SELECT * FROM jobs WHERE id=?',(jid,)).fetchone();run=c.execute('SELECT * FROM runs WHERE id=?',(rid,)).fetchone();c.close();self.assertEqual(d['directive'],'forget');self.assertEqual(job['cleanup_state'],'confirmed');self.assertEqual(run['cleanup_confirmed'],1)
 def test_handler_terminal_progress_and_late_completion_content(self):
  rid,jid,j=self.make_job();c=self.c();self.m.finish(c,j,'failed',10,'network error',failure_code='network',cleanup_confirmed=False);c.close();h=self.handler();h.progress('w1',jid,{'execution_token':'token-1','elapsed_seconds':20});self.assertEqual(h.responses[-1][1]['directive'],'stop_and_cleanup');self.assertFalse(h.responses[-1][1]['accepted']);h.complete('w1',jid,{'execution_token':'token-1','status':'failed','cleanup_confirmed':True});self.assertEqual(h.responses[-1][1]['directive'],'forget');c=self.c();self.assertIsNone(c.execute('SELECT quarantine_reason FROM jobs WHERE id=?',(jid,)).fetchone()[0]);c.close()
 def test_start_admission_excludes_leased_job_at_one_and_full_capacity(self):
  for capacity,other_count in ((1,0),(3,2)):
   with self.subTest(capacity=capacity):
    if capacity==3:
     for aid in (11,12):self.make_job(aid=aid)
    self.worker(capacity=capacity)
    c=self.c();c.execute('BEGIN IMMEDIATE');c.execute("UPDATE settings SET value='0'");a=self.m.acc(c,10);rid,jid,_=self.m.create(c,a,300,'manual',manual=True);c.execute("UPDATE jobs SET status='leased',worker_id='w1',execution_generation=1,execution_token='token-1',execution_state='leased' WHERE id=?",(jid,));c.execute("UPDATE runs SET status='leased' WHERE id=?",(rid,));c.commit();c.close();h=self.handler();h.wstart('w1',jid,{'execution_token':'token-1'});self.assertTrue(h.responses[-1][1]['ok']);c=self.c();self.assertEqual(c.execute('SELECT status FROM jobs WHERE id=?',(jid,)).fetchone()[0],'running');c.close();break
 def test_queued_jobs_reserve_capacity_and_resources(self):
  self.worker();c=self.c();c.execute('BEGIN IMMEDIATE');c.execute("UPDATE settings SET value='0'")
  created=[]
  for aid in (10,11,12):created.append(self.m.create(c,self.m.acc(c,aid),300,'manual',manual=True))
  with self.assertRaises(self.m.E) as x:self.m.create(c,self.m.acc(c,13),300,'manual',manual=True)
  w=self.m.authoritative_workload(c);c.rollback();c.close();self.assertEqual(x.exception.code,'capacity_full');self.assertEqual(w['occupied'],3);self.assertEqual(w['states']['queued'],3);self.assertEqual(w['available_slots'],0)
 def test_heartbeat_execution_and_legacy_resource_locks(self):
  self.worker(executions=[{'job_id':999,'profile_id':'ghost-profile','proxy_port':11999,'account_id':999}],active_profiles=['legacy-profile'],active_ports=[11998]);c=self.c();w=self.m.authoritative_workload(c);c.close();self.assertIn('ghost-profile',w['active_profile_ids']);self.assertIn('legacy-profile',w['active_profile_ids']);self.assertIn(11999,w['active_proxy_ports']);self.assertIn(11998,w['active_proxy_ports'])
 def test_retry_survives_global_pause_and_runs_after_resume(self):
  rid,jid,j=self.make_job();c=self.c();c.execute("UPDATE settings SET value='1'");self.m.finish(c,j,'failed',10,'network error',failure_code='network',cleanup_confirmed=True,retry_delay=0);r=c.execute('SELECT * FROM runs WHERE id=?',(rid,)).fetchone();self.assertEqual(r['retry_eligible'],1);self.assertIsNotNone(r['retry_not_before']);self.assertEqual(r['retry_block_reason'],'global_pause');before=c.execute('SELECT COUNT(*) FROM runs').fetchone()[0];self.m.scheduler_fill(c,self.m.now()+1);self.assertEqual(c.execute('SELECT COUNT(*) FROM runs').fetchone()[0],before);c.execute("UPDATE settings SET value='0'");c.execute("UPDATE accounts SET auto_schedule_enabled=1,daily_window_start='00:00',daily_window_end='23:59' WHERE id=10");c.execute("UPDATE jobs SET status='failed' WHERE id=?",(jid,));self.m.scheduler_fill(c,self.m.now()+1);self.assertEqual(c.execute('SELECT COUNT(*) FROM runs WHERE retry_of_run_id=?',(rid,)).fetchone()[0],1);c.close()
 def test_legacy_cleanup_semantics_and_capabilities(self):
  rid,jid,j=self.make_job(tokens=False);c=self.c();self.assertTrue(self.m.finish(c,j,'failed',10,'network error',failure_code='network',cleanup_confirmed=False));self.assertEqual(c.execute('SELECT status FROM jobs WHERE id=?',(jid,)).fetchone()[0],'quarantined');c.close()
  rid,jid,j=self.make_job(aid=11,tokens=False);c=self.c();self.assertTrue(self.m.finish(c,j,'succeeded',10));self.assertEqual(c.execute('SELECT status FROM jobs WHERE id=?',(jid,)).fetchone()[0],'succeeded');c.execute("UPDATE accounts SET login_status='pending_manual_login' WHERE id=12");a=self.m.acc(c,12);p=self.m.plan(c,12);h=self.handler();self.assertIsNone(h.block_reason(c,a,p,'probe'));self.assertEqual(h.block_reason(c,a,p,'manual'),'manual_action_required');c.close()
 def test_current_issue_is_not_historical_failure_and_settings_allowed(self):
  rid,jid,j=self.make_job();c=self.c();self.m.finish(c,j,'failed',10,'network error',failure_code='network',cleanup_confirmed=True);a=self.m.acc(c,10);h=self.handler();view=h.normalized_account(c,a);c.close();self.assertIsNone(view['current_issue']);self.assertIsNotNone(view['last_failure']);self.assertTrue(view['capabilities']['settings']['allowed']);self.assertEqual(view['capabilities'],view['account_capabilities'])
 def test_unhealthy_login_is_current_issue_without_run(self):
  c=self.c();c.execute("UPDATE accounts SET login_status='pending_manual_login' WHERE id=22");a=self.m.acc(c,22);view=self.handler().normalized_account(c,a);c.close();self.assertEqual(view['current_issue']['code'],'authentication');self.assertEqual(view['current_issue']['facts']['login_status'],'pending_manual_login');self.assertIsNone(view['current_issue']['context']);self.assertIsNone(view['last_failure'])
 def test_historical_manual_action_is_only_last_failure_after_login_recovers(self):
  rid,jid,j=self.make_job();c=self.c();self.m.finish(c,j,'manual_action_required',10,'Captcha requires manual action',login_status='pending_manual_login',failure_code='authentication',cleanup_confirmed=True);c.execute("UPDATE accounts SET login_status='logged_in' WHERE id=10");a=self.m.acc(c,10);view=self.handler().normalized_account(c,a);c.close();self.assertIsNone(view['current_issue']);self.assertEqual(view['last_failure']['status'],'manual_action_required');self.assertEqual(view['last_failure']['failure_code'],'authentication')
 def test_unhealthy_login_uses_latest_failure_only_as_context(self):
  rid,jid,j=self.make_job();c=self.c();self.m.finish(c,j,'failed',10,'Proxy failed previously',failure_code='proxy',cleanup_confirmed=True);c.execute("UPDATE accounts SET login_status='restricted' WHERE id=10");a=self.m.acc(c,10);view=self.handler().normalized_account(c,a);c.close();self.assertEqual(view['current_issue']['code'],'authentication');self.assertEqual(view['current_issue']['facts']['login_status'],'restricted');self.assertEqual(view['current_issue']['context']['latest_detail'],'Proxy failed previously');self.assertIn('latest detail',view['current_issue']['message'])
 def test_active_cleanup_precedes_login_issue(self):
  rid,jid,j=self.make_job();c=self.c();c.execute("UPDATE accounts SET login_status='logged_out' WHERE id=10");c.execute("UPDATE jobs SET status='cleaning',cleanup_state='cleaning' WHERE id=?",(jid,));a=self.m.acc(c,10);view=self.handler().normalized_account(c,a);c.close();self.assertEqual(view['current_issue']['code'],'cleanup_pending')

if __name__=='__main__':unittest.main()
